<?php

/**
 * @file
 * Theme functions.
 */
function playground_preprocess_views_view(&$variables) {
  if ($variables['view']->id() === 'software_library_search') {
    // Attach library
    $variables['#attached']['library'][] = 'playground/software-library';
    // Pass current user roles to Twig
    $variables['user_roles'] = \Drupal::currentUser()->getRoles();
  }
}
// Include all files from the includes directory.
$includes_path = __DIR__ . '/includes/*.theme';
foreach (glob($includes_path) as $file) {
  require_once __DIR__ . '/includes/' . basename($file);

  
}
